sonar.projectKey=Lidianacosta_BackendFinanSee
sonar.projectName=BackendFinanSee
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/__pycache__/**, **/*.sqlite, **/.venv/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=coverage.xml

sonar.sourceEncoding=UTF-8
sonar.language=py
